# action.yml
name: "Consul KV Submit"
author: "Darryl Mendillo"
description: "Submit all config file with matching regex to Consul"
branding:
  icon: "database"
  color: "red"
inputs:
  addr:
    description: "The HTTP address for Consul"
    required: true
  config:
    description: "deploy_config.yml file with all deployment settings"
    required: true
  env:
    description: "Deployment environment ot override deploy_config.yml. ex: staging, production"
    required: false
    default: 'staging'

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    CONSUL_HTTP_ADDR: ${{ inputs.addr }}
    DEPLOY_CONFIG: ${{ inputs.config }}
    ENV: ${{ inputs.env }}