# action.yml
name: "Consul KV Submit"
author: "Darryl Mendillo"
description: "Submit all config file with matching regex to Consul"
branding:
  icon: "database"
  color: "red"
inputs:
  addr:
    description: "The HTTP address for Consul"
    required: true
  config:
    description: "deploy_config.yml file with all deployment settings"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.addr }}
    - ${{ inputs.config }}
