# action.yml
name: "Consul KV Submit"
author: "Darryl Mendillo"
description: "Submit all config file with matching regex to Consul"
branding:
  icon: "database"
  color: "red"
inputs:
  addr:
    description: "The HTTP address for Consul"
    required: true
  path:
    description: "Path to submit files in Consul. Do not include deploy environment (staging/production). Format: path/to/key Default to \"\"."
    required: false
    default: ""
  regex:
    description: "Regex for files to submit"
    required: true    
  locations:
    description: "Search locations for config files. Defaults to GITHUB_WORKSPACE"
    default: "./"
    required: false
  deploy:
      description: "Deployment environent. Submits only configs matching environment, and renames them. Example (staging.yaml -> config.yaml) Defaults to staging"
      default: "staging"
      required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.addr }}
    - ${{ inputs.path }}
    - ${{ inputs.regex }}
    - ${{ inputs.location }}
