version: "3.8"

services:

  consul:
    build: .
    #entrypoint: /bin/bash
    environment:
      CONSUL_HTTP_ADDR: "http://10.145.240.242:8500"
      DEPLOY_CONFIG: "local/deploy_config.yml"
      ENV: "production"
    restart: always
    stdin_open: true # docker run -i
    stop_signal: SIGTERM
    tty: true        # docker run -t
    volumes:
    - /Users/dmendillo/Documents/GitHub/palliativeconnect:/source/
    working_dir: /source
