version: "3.8"

services:

  consul:
    build: .
    entrypoint: /bin/bash
    environment:
    - INPUT_ADDR=http://10.146.0.5:8500/v1/kv
    - INPUT_CONFIG=deploy_config.yml
    restart: always
    stdin_open: true # docker run -i
    stop_signal: SIGTERM
    tty: true        # docker run -t
    volumes:
    - ./:/source/
    working_dir: /source